version: '3.4'

services: 
  todo-api:
    build:
      context: .
      dockerfile: TodoApi/Dockerfile
#    image: todo-api
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASS}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/https/todoapi.pfx
      - 'ConnectionStrings:DefaultConnection=Data Source = db.sqlite'
      - 'Jwt:Key=this is the secret key for the jwt, it must be kept secure'
      - 'Jwt:Issuer=todo.chessmax.ru'
      - 'Jwt:Audience=todo.chessmax.ru'
      - 'Jwt:Subject=JWT for todo.chessmax.ru'
      - DetailedErrors=true
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https:ro
      - ./TodoApi/.cert/:/app/https/
    container_name: todo-api
    
volumes: 
  todo-data: